// <auto-generated />
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBook.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607141232_ProductTableSeed")]
    partial class ProductTableSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tolkien",
                            Description = "",
                            ISBN = "1231412",
                            ListPrice = 15.0,
                            Price = 12.0,
                            Price100 = 8.0,
                            Price50 = 10.0,
                            Title = "Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Herbert",
                            Description = "",
                            ISBN = "4124123",
                            ListPrice = 22.0,
                            Price = 18.0,
                            Price100 = 12.0,
                            Price50 = 15.0,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Josephg",
                            Description = "asdasd",
                            ISBN = "6344533",
                            ListPrice = 17.0,
                            Price = 16.0,
                            Price100 = 8.0,
                            Price50 = 10.0,
                            Title = "Series of Unfortonate Events"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Patrick Rothfuss",
                            Description = "",
                            ISBN = "1231412",
                            ListPrice = 33.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "Name Of the Wind"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
